server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
    hostname: localhost
    port: 8899
    contextPath: userauth

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
spring:
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 
      
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory1?autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver
    jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
    jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
---  
jsondoc:
 version: 1.0
 basePath: http://localhost:8081
 packages[0]: com.lenskart.order.controller
 packages[1]: com.lenskart.order.model
 displayMethodAs: URI   
